runtime: php82
runtime_config:
  document_root: gcp-php-mysql
env_variables:
  MYSQL_HOST: mysql:unix_socket=/cloudsql/appdeploy-402517:us-central1:lincbd
  MYSQL_DB: lincdb
  MYSQL_USER: root
  MYSQL_PASS: linc@2023
