runtime: php82
env: flex

runtime_config:
  document_root: public

env_variables:
  DB_CONNECTION: mysql
  DB_HOST: localhost # Utilisez le chemin de connexion Cloud SQL
  DB_DATABASE: lincd
  DB_USERNAME: phpmyadmin
  DB_PASSWORD: linc@2023
  DB_SOCKET: "appdeploy-402517:us-central1:plateforme"  # Spécifiez le socket pour Cloud SQL
