runtime: php82
env: flex

runtime_config:
  document_root: public
skip_files:
    - .env

env_variables:
  DB_CONNECTION: mysql
  DB_HOST: localhost # Utilisez le chemin de connexion Cloud SQL
  DB_DATABASE: lincd
  DB_USERNAME: phpmyadmin
  DB_PASSWORD: linc@2023
